doctrine:
  orm:
    entity_managers:
      fipps:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          FippsNewsauthorBundle:
            type: yml